font:
          # Normal (roman) font face
        normal:
            family: Source Code Pro for Powerline
            # The `style` can be specified to pick a specific face.
            # style: Regular

        size: 8.5

        offset:
            x: 0
            y: 1

        glyph_offset:
            x: 0
            y: 0

# Colors (Darkside)
colors:
  primary:
    background: '#222324'
    foreground: '#BABABA'

  # Normal colors
  normal:
    black:    '#000000'
    red:      '#E8341C'
    green:    '#68C256'
    yellow:   '#F2D42C'
    blue:     '#1C98E8'
    magenta:  '#8E69C9'
    cyan:     '#1C98E8'
    white:    '#BABABA'

  # Bright colors
  bright:
    black:    '#666666'
    red:      '#E05A4F'
    green:    '#77B869'
    yellow:   '#EFD64B'
    blue:     '#387CD3'
    magenta:  '#957BBE'
    cyan:     '#3D97E2'
    white:    '#BABABA'

    # background_opacity: 0
